# Mueller module

In [1]:
%run ../config_jupyter.ipynb
%autoreload 2

from math import sqrt

from py_pol.mueller import Mueller
from py_pol.stokes import Stokes
from py_pol.jones_matrix import Jones_matrix
from py_pol.utils import rotation_matrix_Mueller, isrow, iscolumn, azimuth_elipt_2_charac_angles, comparison

from py_pol import degrees
import numpy as np

eps = 1e-6

{'commit_hash': '523ed2fe5',
 'commit_source': 'installation',
 'default_encoding': 'cp1252',
 'ipython_path': 'C:\\Users\\jesus\\Anaconda3\\lib\\site-packages\\IPython',
 'ipython_version': '7.2.0',
 'os_name': 'nt',
 'platform': 'Windows-10-10.0.17763-SP0',
 'sys_executable': 'C:\\Users\\jesus\\Anaconda3\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit '
                '(AMD64)]'}
3.0.2


## Checks

In [4]:
# Print
M1 = Mueller()
M1.diattenuator_linear(p1=1, p2=0)
print(M1.checks)

Checks for M:
    Is physically realizable    : True
    Is pure (do not depolarize) : True
      - Is homogenous           : True
      - Is a retarder           : False
      - Is a diattenuator       : True
    Is singular                 : True



In [2]:
# Test funcionamiento padre
M1 = Mueller()
M1.diattenuator_linear(p1=1, p2=0)
d = M1.checks.method_test()
print(d)

1.0
M = 
  [+0.500, +0.500, +0.000, +0.000]
  [+0.500, +0.500, +0.000, +0.000]
  [+0.000, +0.000, +0.000, +0.000]
  [+0.000, +0.000, +0.000, +0.000]



In [3]:
# is_physical
(p1, p2, alpha, delta) = np.random.rand(4)
M1 = Mueller('M1')
M1.diattenuator_charac_angles_from_Jones(p1, p2, alpha*90*degrees, delta*360*degrees)
proposal = M1.checks.is_physical()
print(proposal)

(D, alpha, delta) = np.random.rand(3)
M1 = Mueller('M1')
M1.retarder_charac_angles_from_Jones(D*180*degrees, alpha*90*degrees, delta*360*degrees)
proposal = M1.checks.is_physical()
print(proposal)

d = np.random.rand(1)
M1 = Mueller('M1')
M1.depolarizer(d[0])
proposal, conds = M1.checks.is_physical(give_all = True)
print(proposal)

True
True
True


In [4]:
# is_non_depolarizing
(p1, p2, alpha, delta) = np.random.rand(4)
M1 = Mueller('M1')
M1.diattenuator_charac_angles_from_Jones(p1, p2, alpha*90*degrees, delta*360*degrees)
proposal = M1.checks.is_non_depolarizing()
print(proposal)

(D, alpha, delta) = np.random.rand(3)
M1 = Mueller('M1')
M1.retarder_charac_angles_from_Jones(D*180*degrees, alpha*90*degrees, delta*360*degrees)
proposal = M1.checks.is_non_depolarizing()
print(proposal)

d = np.random.rand(3)*.95
M1 = Mueller('M1')
M1.depolarizer(d)
proposal, conds = M1.checks.is_non_depolarizing(give_all = True)
print(proposal)

d = np.random.rand(1)
M1 = Mueller('M1')
M1.depolarizer(d[0])
proposal, conds = M1.checks.is_non_depolarizing(give_all = True)
print(proposal)

True
True
False
False


In [5]:
# is_homogeneous
(p1, p2, alpha, delta) = np.random.rand(4)
M1 = Mueller('M1')
M1.diattenuator_charac_angles_from_Jones(p1, p2, alpha*90*degrees, delta*360*degrees)
proposal = M1.checks.is_homogeneous()
print(proposal)

(D, alpha, delta) = np.random.rand(3)
M1 = Mueller('M1')
M1.retarder_charac_angles_from_Jones(D*180*degrees, alpha*90*degrees, delta*360*degrees)
proposal = M1.checks.is_homogeneous()
print(proposal)

d = np.random.rand(3)*.95
M1 = Mueller('M1')
M1.depolarizer(d)
proposal = M1.checks.is_homogeneous()
print(proposal)

True
True
True


d:\codigo\py_pol\py_pol\mueller.py:1402: RuntimeWarning: invalid value encountered in sqrt
  return sqrt(eta)


In [7]:
# Is retarder
(p1, p2, alpha, delta) = np.random.rand(4)
M1 = Mueller('M1')
M1.diattenuator_charac_angles_from_Jones(p1, p2, alpha*90*degrees, delta*360*degrees)
proposal = M1.checks.is_retarder()
print(proposal)

(D, alpha, delta) = np.random.rand(3)
M1 = Mueller('M1')
M1.retarder_charac_angles_from_Jones(D*180*degrees, alpha*90*degrees, delta*360*degrees)
proposal = M1.checks.is_retarder()
print(proposal)

d = np.random.rand(3)*.95
M1 = Mueller('M1')
M1.depolarizer(d)
proposal = M1.checks.is_retarder()
print(proposal)


False
True
False


In [8]:
# is_diattenuator
(p1, p2, alpha, delta) = np.random.rand(4)
M1 = Mueller('M1')
M1.diattenuator_charac_angles_from_Jones(p1, p2, alpha*90*degrees, delta*360*degrees)
proposal = M1.checks.is_diattenuator()
print(proposal)

(D, alpha, delta) = np.random.rand(3)
M1 = Mueller('M1')
M1.retarder_charac_angles_from_Jones(D*180*degrees, alpha*90*degrees, delta*360*degrees)
proposal = M1.checks.is_diattenuator()
print(proposal)

d = np.random.rand(3)*.95
M1 = Mueller('M1')
M1.depolarizer(d)
proposal = M1.checks.is_diattenuator()
print(proposal)


True
False
False


In [10]:
# is_singular
(p1, p2, alpha, delta) = np.random.rand(4)
M1 = Mueller('M1')
M1.diattenuator_charac_angles_from_Jones(p1, p2, alpha*90*degrees, delta*360*degrees)
proposal = M1.checks.is_singular()
print(proposal)

(p1, alpha, delta) = np.random.rand(3)
p2 = 0
M1 = Mueller('M1')
M1.diattenuator_charac_angles_from_Jones(p1, p2, alpha*90*degrees, delta*360*degrees)
proposal = M1.checks.is_singular()
print(proposal)

(D, alpha, delta) = np.random.rand(3)
M1 = Mueller('M1')
M1.retarder_charac_angles_from_Jones(D*180*degrees, alpha*90*degrees, delta*360*degrees)
proposal = M1.checks.is_singular()
print(proposal)

d = [1, 0, 1]
M1 = Mueller('M1')
M1.depolarizer(d)
proposal = M1.checks.is_singular()
print(proposal)

False
True
False
True


In [11]:
# is_pure
(p1, p2, alpha, delta) = np.random.rand(4)
M1 = Mueller('M1')
M1.diattenuator_charac_angles_from_Jones(p1, p2, alpha*90*degrees, delta*360*degrees)
proposal = M1.checks.is_pure()
print(proposal)

(D, alpha, delta) = np.random.rand(3)
M1 = Mueller('M1')
M1.retarder_charac_angles_from_Jones(D*180*degrees, alpha*90*degrees, delta*360*degrees)
proposal = M1.checks.is_pure()
print(proposal)

d = np.random.rand(3)*.95
M1 = Mueller('M1')
M1.depolarizer(d)
proposal = M1.checks.is_pure()
print(proposal)

True
True
False


## Analyze

### Filtrado

In [12]:
original = np.matrix(
    np.array([[1, -0.0229, 0.0027, 0.0058], [-0.0186, 0.9956, -0.0361, 0.0318], [-0.0129, 0.0392, 0.2207, -0.9656],
              [0.0014, 0.0280, 0.9706, 0.2231]]))
M = np.matrix(np.random.rand(4,4))
M1 = Mueller('M1')
M1.from_matrix(M)
proposal = M1.analysis.filter_physical_conditions(give_object=False, verbose=True, tol=0.01)

The original matrix is:
[[0.30937013 0.86379252 0.41399426 0.90139898]
 [0.0056926  0.17925788 0.67288969 0.81634714]
 [0.83209471 0.51735076 0.75333793 0.415891  ]
 [0.1041931  0.24047023 0.60705331 0.837917  ]]
Second condition was violated. Fixed matrix is:
[[0.30937013 0.30937013 0.30937013 0.30937013]
 [0.0056926  0.17925788 0.30937013 0.30937013]
 [0.30937013 0.30937013 0.30937013 0.30937013]
 [0.1041931  0.24047023 0.30937013 0.30937013]]
The original matrix is:
[[0.30937013 0.30937013 0.30937013 0.30937013]
 [0.0056926  0.17925788 0.30937013 0.30937013]
 [0.30937013 0.30937013 0.30937013 0.30937013]
 [0.1041931  0.24047023 0.30937013 0.30937013]]
Third A condition was violated. Fixed matrix is:
[[0.30937013 0.17861493 0.17861493 0.17861493]
 [0.0056926  0.17925788 0.30937013 0.30937013]
 [0.30937013 0.30937013 0.30937013 0.30937013]
 [0.1041931  0.24047023 0.30937013 0.30937013]]
The original matrix is:
[[0.30937013 0.17861493 0.17861493 0.17861493]
 [0.0056926  0.17925788 0.30

### Parametros de diatenuador

In [196]:
# From charac
N = 20
x = np.zeros(N)
for ind in range(N):
    (p1a, p2a, alpha, delta) = np.random.rand(4)
    alpha = alpha*90*degrees
    delta = delta*360*degrees
    p1 = max(p1a, p2a)
    p2 = min(p1a, p2a)
    solution = (p1, p2, alpha, delta)
    M1 = Mueller('M1')
    M1.diattenuator_charac_angles_from_Jones(p1, p2, alpha, delta)
    proposal = M1.analysis.diattenuator(param = 'charac')
    proposal = np.array(proposal)
    x[ind] = np.linalg.norm(solution-proposal)
print(np.linalg.norm(x))

6.064441680297109e-15


In [7]:
print(M1.D)

[[ 0.94799691 -0.06589673 -0.01648559]]


In [75]:
(p1a, p2a, azimuth, ellipticity) = np.random.rand(4)
azimuth = azimuth*180*degrees
ellipticity = (1-ellipticity*2)*45*degrees
p1 = max(p1a, p2a)
p2 = min(p1a, p2a)
solution = np.array([p1, p2, azimuth, ellipticity])
M1 = Mueller('M1')
M1.diattenuator_azimuth_ellipticity_from_vector(p1, p2, azimuth, ellipticity)
proposal = M1.analysis.diattenuator(param = 'azel')
proposal = np.array(proposal)
print(azimuth/degrees)
print(M1)
print(solution)
print(proposal)
print(np.linalg.norm(solution-proposal))

113.79287516518593
M1 = 
  [+0.487, -0.267, -0.292, +0.172]
  [-0.267, +0.325, +0.110, -0.065]
  [-0.292, +0.110, +0.345, -0.071]
  [+0.172, -0.065, -0.071, +0.266]

[0.9581786  0.23464201 1.98606034 0.20488422]
[0.9581786  0.23464201 1.98606034 0.20488422]
2.9504581591051765e-16


### Parametros retardador

In [197]:
# From charac
N = 20
errors = np.zeros(N)
for ind in range(N):
    (delta, alpha, delay) = np.random.rand(3)
    delta = delta*180*degrees
    alpha = alpha*90*degrees
    delay = delay*360*degrees
    solution = (delta, alpha, delay)
    M1 = Mueller('M1')
    M1.retarder_charac_angles_from_Jones(delta, alpha, delay)
    proposal = M1.analysis.retarder(param = 'charac')
    proposal = np.array(proposal)
    errors[ind] = comparison(proposal, solution, eps)
print(errors)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [198]:
for ind in range(N):
    (delta, azimuth, ellipticity) = np.random.rand(3)
    delta = delta*180*degrees
    azimuth = azimuth*90*degrees
    ellipticity = ellipticity*360*degrees
    solution = (delta, azimuth, ellipticity)
    M1 = Mueller('M1')
    M1.retarder_charac_angles_from_Jones(delta, azimuth, ellipticity)
    proposal = M1.analysis.retarder(param = 'charac')
    proposal = np.array(proposal)
    errors[ind] = comparison(proposal, solution, eps)
print(errors)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Decompose

### Pure matrices

In [18]:
# Polarizer right
N = 20
errors = np.zeros(N)
for ind in range(N):
    # Create random parameters
    (p1a, p2a, alphaP, delayP, delta, alphaR, delayR) = np.random.rand(7)
    p1 = max(p1a, p2a)
    p2 = min(p1a, p2a)
    alphaP = alphaP*90*degrees
    delayP = delayP*360*degrees
    delta = delta*180*degrees
    alphaR = alphaR*90*degrees
    delayR = delayR*360*degrees     
#     solution = (p1, p2, alphaP, delayP, delta, alphaR, delayR)
    # Create objects 
    M1 = Mueller('Mp')
    M1.diattenuator_charac_angles_from_Jones(p1, p2, alphaP, delayP)
    M2 = Mueller('Mr')
    M2.retarder_charac_angles_from_Jones(delta, alphaR, delayR)
    M = M2*M1
    # Decompose
    Mr, Md, params = M.analysis.decompose_pure(give_all = True, tol=1e-10)
    aux = [comparison(Md.M, M1.M, eps), comparison(Mr.M, M2.M, eps)]
#     print(aux)   
#     print([delta, alphaR, delayR])
#     print(Mr.analysis.retarder())
#     print("")
#     print([Mr, M2])
#     print([Md, M1])
    errors[ind] = all(aux)
print(errors)
Mr, Md = M.analysis.decompose_pure(tol=1e-10, verbose=True)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
------------------------------------------------------
Matrx M decomposed as M = Mr * Md.

The retarder Mueller matrix is:
retarder = 
  [+1.000, -0.000, +0.000, -0.000]
  [+0.000, -0.158, -0.843, -0.515]
  [-0.000, -0.929, -0.051, +0.367]
  [+0.000, -0.336, +0.536, -0.774]

Parameters:
  - Delay = 172.5019105481461 deg.
  - Angle = 65.15811542611777 deg; Delay between components = 25.65661979298176 deg.
  - Azimuth = 66.63497099953481 deg; Ellipticity = 9.6385848158921 deg.

The diatenuator Mueller matrix is:
diattenuator = 
  [+0.402, -0.153, +0.155, -0.159]
  [-0.153, +0.332, -0.034, +0.035]
  [+0.155, -0.034, +0.333, -0.035]
  [-0.159, +0.035, -0.035, +0.335]

Parameters:
  - p1 = 0.8195822321647781; p2 = 0.3646279501492804.
  - Angle = 62.26639839928088 deg; Delay between components = 314.2926166566457 deg.
  - Azimuth = 67.28926448122508 deg; Ellipticity = -18.06655310324078 deg.

The mean square error in the decomposi

In [21]:
# From charac
N = 20
errors = np.zeros(N)
for ind in range(N):
    # Create random parameters
    (p1a, p2a, alphaP, delayP, delta, alphaR, delayR) = np.random.rand(7)
    p1 = max(p1a, p2a)
    p2 = min(p1a, p2a)
    alphaP = alphaP*90*degrees
    delayP = delayP*360*degrees
    delta = delta*180*degrees
    alphaR = alphaR*90*degrees
    delayR = delayR*360*degrees     
#     solution = (p1, p2, alphaP, delayP, delta, alphaR, delayR)
    # Create objects 
    M1 = Mueller('Mp')
    M1.diattenuator_charac_angles_from_Jones(p1, p2, alphaP, delayP)
    M2 = Mueller('Mr')
    M2.retarder_charac_angles_from_Jones(delta, alphaR, delayR)
    M = M1*M2
    # Decompose
    Mr, Md, params = M.analysis.decompose_pure(decomposition='PR', give_all = True, tol=1e-10)
    aux = [comparison(Md.M, M1.M, eps), comparison(Mr.M, M2.M, eps)]
#     print(aux)   
#     print([delta, alphaR, delayR])
#     print(Mr.analysis.retarder())
#     print("")
#     print([Mr, M2])
    errors[ind] = all(aux)
print(errors)
Mr, Md = M.analysis.decompose_pure(tol=1e-10, verbose=True)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
------------------------------------------------------
Matrx M decomposed as M = Mr * Md.

The retarder Mueller matrix is:
retarder = 
  [+1.000, +0.000, +0.000, -0.000]
  [-0.000, -0.657, -0.753, +0.016]
  [+0.000, +0.752, -0.657, -0.041]
  [+0.000, +0.042, -0.015, +0.999]

Parameters:
  - Delay = 131.14563549872548 deg.
  - Angle = 45.499093836990966 deg; Delay between components = 270.97162703779924 deg.
  - Azimuth = 67.88839475590622 deg; Ellipticity = -44.30351916438792 deg.

The diatenuator Mueller matrix is:
diattenuator = 
  [+0.405, +0.315, +0.165, -0.165]
  [+0.315, +0.298, +0.103, -0.102]
  [+0.165, +0.103, +0.155, -0.054]
  [-0.165, -0.102, -0.054, +0.155]

Parameters:
  - p1 = 0.892990135600081; p2 = 0.11361350810737245.
  - Angle = 18.25988928784572 deg; Delay between components = 315.1218854113679 deg.
  - Azimuth = 13.843492970560224 deg; Ellipticity = -12.414241251866738 deg.

The mean square error in the d

In [23]:
# Casos particulares
# Solo un retardador
for ind in range(N):
    # Create random parameters
    (delta, alphaR, delayR) = np.random.rand(3)
    delta = delta*180*degrees
    alphaR = alphaR*90*degrees
    delayR = delayR*360*degrees     
#     solution = (p1, p2, alphaP, delayP, delta, alphaR, delayR)
    # Create objects 
    M1 = Mueller('Mp')
    M1.from_matrix(np.eye(4))
    M2 = Mueller('Mr')
    M2.retarder_charac_angles_from_Jones(delta, alphaR, delayR)
    M = M1*M2
    # Decompose
    Mr, Md, params = M.analysis.decompose_pure(give_all = True, tol=1e-10)
    aux = [comparison(Md.M, M1.M, eps), comparison(Mr.M, M2.M, eps)]
#     print(aux)   
#     print([delta, alphaR, delayR])
#     print(Mr.analysis.retarder())
#     print("")
#     print([Mr, M2])
    errors[ind] = all(aux)
print(errors)

# Matriz singular (p2=0)
p2 = 0
for ind in range(N):
    # Create random parameters
    (p1, alphaP, delayP, delta, alphaR, delayR) = np.random.rand(6)
    alphaP = alphaP*90*degrees
    delayP = delayP*360*degrees
    delta = delta*180*degrees
    alphaR = alphaR*90*degrees
    delayR = delayR*360*degrees     
#     solution = (p1, p2, alphaP, delayP, delta, alphaR, delayR)
    # Create objects 
    M1 = Mueller('Mp')
    M1.diattenuator_charac_angles_from_Jones(p1, p2, alphaP, delayP)
    M2 = Mueller('Mr')
    M2.retarder_charac_angles_from_Jones(delta, alphaR, delayR)
    M = M2*M1
    # Decompose
    Mr, Md, params = M.analysis.decompose_pure(give_all = True, tol=1e-10)
    Mproposal = Mr*Md
#     print(comparison(Md.M, M1.M, eps))   
#     print([delta, alphaR, delayR])
#     print(Mr.analysis.retarder())
#     print("")
#     print([Mr, M2])
#     print(M,Mproposal)
    errors[ind] = comparison(M.M, Mproposal.M, eps)
    if not errors[ind]:
        print(Md)
print(errors)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [60]:
R = 0.85529196
Rv = np.array([-0.04781196,  0.51911958,  0.85336327])
MR = Mueller()
MR.retarder_from_vector(R, Rv)
print(MR)

M = 
  [+1.000, +0.000, +0.000, +0.000]
  [+0.000, +0.657, +0.635, -0.406]
  [+0.000, -0.653, +0.749, +0.116]
  [+0.000, +0.378, +0.189, +0.906]



### Depolarizing matrices

In [24]:
# Caso general
N = 20
errors = np.zeros(N)
for ind in range(N):
    # Create random parameters
    (p1a, p2a, alphaP, delayP, delta, alphaR, delayR) = np.random.rand(7)
    d = 0.95 * np.random.rand(3)
    p1 = max(p1a, p2a)
    p2 = min(p1a, p2a)
    alphaP = alphaP*90*degrees
    delayP = delayP*360*degrees
    delta = delta*180*degrees
    alphaR = alphaR*90*degrees
    delayR = delayR*360*degrees     
#     solution = (p1, p2, alphaP, delayP, delta, alphaR, delayR)
    # Create objects 
    M1 = Mueller('Mp')
    M1.diattenuator_charac_angles_from_Jones(p1, p2, alphaP, delayP)
    M2 = Mueller('Mr')
    M2.retarder_charac_angles_from_Jones(delta, alphaR, delayR)
    M3 = Mueller('Md')
    M3.depolarizer(d)
#     M3.from_matrix(np.eye(4))
    M = M3*M2*M1
#     print(M.checks.is_non_depolarizing())
#     print(M)
    # Decompose
    Md, Mr, Mp = M.analysis.decompose_polar(tol=1e-10, verbose = False)
    aux = [comparison(Mp.M, M1.M, eps), comparison(Mr.M, M2.M, eps), comparison(Md.M, M3.M, eps)]
#     print(aux)   
#     print([delta, alphaR, delayR])
#     print(Mr.analysis.retarder())
#     print("")
#     print([M3, Md])
#     print([M2, Mr])
#     print([M1, M, Mp])
    errors[ind] = all(aux)
print(errors)
Md, Mr, Mp, params = M.analysis.decompose_polar(tol=1e-10, verbose=True, give_all=True)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
------------------------------------------------------
General case.
Polar decomposition of the matrix M = Mdesp * Mr * Mp:

The depolarizer Mueller matrix is:
depolarizer = 
  [+1.000, +0.000, +0.000, +0.000]
  [+0.000, +0.827, +0.000, +0.000]
  [-0.000, +0.000, +0.117, +0.000]
  [-0.000, +0.000, +0.000, +0.357]

Parameters:
  - Polarizance = 3.0808325543336005e-17.
  - Depolarization degree = 0.8515622717289576.

The retarder Mueller matrix is:
retarder = 
  [+1.000, +0.000, +0.000, +0.000]
  [+0.000, -0.180, +0.079, +0.981]
  [+0.000, +0.205, +0.978, -0.041]
  [+0.000, -0.962, +0.194, -0.192]

Parameters:
  - Delay = 101.35640239726428 deg.
  - Angle = 48.439806216333565 deg; Delay between components = 183.73030326941256 deg.
  - Azimuth = 131.5529607720262 deg; Ellipticity = -1.8517037927501643 deg.

The diatenuator/polarizer Mueller matrix is:
diattenuator = 
  [+0.073, +0.008, -0.003, +0.014]
  [+0.008, +0.071, -0.000,

In [25]:
# Det Md = 0
# Range(Md) = 3
N = 20
errors = np.zeros(N)
for ind in range(N):
    # Create random parameters
    (p1a, p2a, alphaP, delayP, delta, alphaR, delayR) = np.random.rand(7)
    d = 0.95 * np.random.rand(3)
    d[-1] = 0
    p1 = max(p1a, p2a)
    p2 = min(p1a, p2a)
    alphaP = alphaP*90*degrees
    delayP = delayP*360*degrees
    delta = delta*180*degrees
    alphaR = alphaR*90*degrees
    delayR = delayR*360*degrees     
    # Create objects 
    M1 = Mueller('Mp')
    M1.diattenuator_charac_angles_from_Jones(p1, p2, alphaP, delayP)
    M2 = Mueller('Mr')
    M2.retarder_charac_angles_from_Jones(delta, alphaR, delayR)
    M3 = Mueller('Md')
    M3.depolarizer(d)
    M = M3*M2*M1
#     print(M.checks.is_non_depolarizing())
#     print(M)
    # Decompose
    Md, Mr, Mp = M.analysis.decompose_polar(tol=1e-10, verbose = False)
    aux = [comparison(Mp.M, M1.M, eps), comparison(Mr.M, M2.M, eps), comparison(Md.M, M3.M, eps)]
#     print(aux)
    Mproposal = Md*Mr*Mp
#     print(aux)   
#     print([delta, alphaR, delayR])
#     print(Mr.analysis.retarder())
#     print("")
#     print([M, Mproposal])
#     print([M3, Md])
#     print([M2, Mr])
#     print([M1, M, Mp])
    errors[ind] = comparison(M.M, Mproposal.M, eps)
print(errors)
Md, Mr, Mp, params = M.analysis.decompose_polar(tol=1e-10, verbose=True, give_all=True)
print(delta/degrees)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
------------------------------------------------------
Depolarized matrix singular case with one null eigenvalue.
Polar decomposition of the matrix M = Mdesp * Mr * Mp:

The depolarizer Mueller matrix is:
depolarizer = 
  [+1.000, +0.000, +0.000, +0.000]
  [+0.000, +0.179, -0.000, +0.000]
  [+0.000, -0.000, +0.482, +0.000]
  [+0.000, +0.000, +0.000, +0.000]

Parameters:
  - Polarizance = 5.3504018429544243e-17.
  - Depolarization degree = 0.9549743053851248.

The retarder Mueller matrix is:
retarder = 
  [+1.000, +0.000, +0.000, +0.000]
  [+0.000, +0.948, +0.319, -0.126]
  [+0.000, -0.298, +0.871, -0.017]
  [+0.000, +0.000, +0.000, +0.920]

Parameters:
  - Delay = 29.620578894416354 deg.
  - Angle = 45.77117528825195 deg; Delay between components = 78.42704806094605 deg.
  - Azimuth = 48.822134881872145 deg; Ellipticity = 39.1630568578431 deg.

The diatenuator/polarizer Mueller matrix is:
diattenuator = 
  [+0.443, -0.144, +

In [26]:
# Det Md = 0
# Range(Md) = 2
N = 20
errors = np.zeros(N)
for ind in range(N):
    # Create random parameters
    (p1a, p2a, alphaP, delayP, delta, alphaR, delayR) = np.random.rand(7)
    d = 0.95 * np.random.rand(3)
    d[1:3] = (0,0)
    p1 = max(p1a, p2a)
    p2 = min(p1a, p2a)
    alphaP = alphaP*90*degrees
    delayP = delayP*360*degrees
    delta = delta*180*degrees
    alphaR = alphaR*90*degrees
    delayR = delayR*360*degrees     
    # Create objects 
    M1 = Mueller('Mp')
    M1.diattenuator_charac_angles_from_Jones(p1, p2, alphaP, delayP)
    M2 = Mueller('Mr')
    M2.retarder_charac_angles_from_Jones(delta, alphaR, delayR)
    M3 = Mueller('Md')
    M3.depolarizer(d)
    M = M3*M2*M1
#     print(M.checks.is_non_depolarizing())
#     print(M)
    # Decompose
    Md, Mr, Mp = M.analysis.decompose_polar(tol=1e-10, verbose = False)
    aux = [comparison(Mp.M, M1.M, eps), comparison(Mr.M, M2.M, 5e-2), comparison(Md.M, M3.M, eps)]
    Mproposal = Md*Mr*Mp
#     print(aux)
#     print(aux)   
#     print([delta, alphaR, delayR])
#     print(Mr.analysis.retarder())
#     print([M, Mproposal])
#     print([M3, Md])
#     print([M2, Mr])
#     print([M1, M, Mp])
#     print("")
    errors[ind] = comparison(M.M, Mproposal.M, 2e-2)
print(errors)
Md, Mr, Mp, params = M.analysis.decompose_polar(tol=1e-10, verbose=True, give_all=True)

[1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0.]
------------------------------------------------------
Depolarized matrix singular case with two null eigenvalues.
Polar decomposition of the matrix M = Mdesp * Mr * Mp:

The depolarizer Mueller matrix is:
depolarizer = 
  [+1.000, +0.000, +0.000, +0.000]
  [+0.000, +0.328, +0.000, +0.000]
  [+0.000, +0.000, +0.000, +0.000]
  [+0.000, +0.000, +0.000, +0.000]

Parameters:
  - Polarizance = 8.164498342106365e-17.
  - Depolarization degree = 0.9819351040848681.

The retarder Mueller matrix is:
retarder = 
  [+1.000, +0.000, +0.000, +0.000]
  [+0.000, +0.800, -0.497, -0.335]
  [+0.000, +0.497, +0.863, -0.092]
  [+0.000, +0.335, -0.092, +0.938]

Parameters:
  - Delay = 36.82847616082614 deg.
  - Angle = 45.0 deg; Delay between components = 123.92494816265386 deg.
  - Azimuth = 45.0 deg; Ellipticity = -28.037525918673065 deg.

The diatenuator/polarizer Mueller matrix is:
diattenuator = 
  [+0.114, -0.036, -0.067, +0.009]
  [-0.036

In [27]:
# Det Md = 0
# Range(Md) = 1
N = 20
errors = np.zeros(N)
for ind in range(N):
    # Create random parameters
    (p1a, p2a, alphaP, delayP, delta, alphaR, delayR) = np.random.rand(7)
    d = 0
    p1 = max(p1a, p2a)
    p2 = min(p1a, p2a)
    alphaP = alphaP*90*degrees
    delayP = delayP*360*degrees
    delta = delta*180*degrees
    alphaR = alphaR*90*degrees
    delayR = delayR*360*degrees     
    # Create objects 
    M1 = Mueller('Mp')
    M1.diattenuator_charac_angles_from_Jones(p1, p2, alphaP, delayP)
    M2 = Mueller('Mr')
    M2.retarder_charac_angles_from_Jones(delta, alphaR, delayR)
    M3 = Mueller('Md')
    M3.depolarizer(d)
    M = M3*M2*M1
#     print(M.checks.is_non_depolarizing())
#     print(M)
    # Decompose
    Md, Mr, Mp = M.analysis.decompose_polar(tol=1e-10, verbose = False)
    aux = [comparison(Mp.M, M1.M, eps), comparison(Mr.M, M2.M, 5e-2), comparison(Md.M, M3.M, eps)]
    Mproposal = Md*Mr*Mp
#     print(aux)
#     print(aux)   
#     print([delta, alphaR, delayR])
#     print(Mr.analysis.retarder())
#     print([M, Mproposal])
#     print([M3, Md])
#     print([M2, Mr])
#     print([M1, M, Mp])
#     print("")
    errors[ind] = comparison(M.M, Mproposal.M, 2e-2)
print(errors)
Md, Mr, Mp, params = M.analysis.decompose_polar(tol=1e-10, verbose=True, give_all=True)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
------------------------------------------------------
Depolarized matrix singular case with three null eigenvalues.
Polar decomposition of the matrix M = Mdesp * Mr * Mp:

The depolarizer Mueller matrix is:
depolarizer = 
  [ +1,  +0,  +0,  +0]
  [ +0,  +0,  +0,  +0]
  [ +0,  +0,  +0,  +0]
  [ +0,  +0,  +0,  +0]

Parameters:
  - Polarizance = 0.0.
  - Depolarization degree = 1.0.

The retarder Mueller matrix is:
retarder = 
  [ +1,  +0,  +0,  +0]
  [ +0,  +1,  +0,  +0]
  [ +0,  +0,  +1,  +0]
  [ +0,  +0,  +0,  +1]

Parameters:
  - Delay = 0.0 deg.
  - Angle = 45.0 deg; Delay between components = 0.0 deg.
  - Azimuth = 45.0 deg; Ellipticity = 0.0 deg.

The diatenuator/polarizer Mueller matrix is:
diattenuator = 
  [+0.020, +0.008, -0.010, -0.011]
  [+0.008, +0.012, -0.003, -0.003]
  [-0.010, -0.003, +0.013, +0.004]
  [-0.011, -0.003, +0.004, +0.014]

Parameters:
  - p1 = 0.191222640805894; p2 = 0.05085697730136976.
  - Angle

In [28]:
# Caso general
N = 20
errors = np.zeros(N)
p2 = 0
for ind in range(N):
    # Create random parameters
    (p1, alphaP, delayP, delta, alphaR, delayR) = np.random.rand(6)
    d = 0.95 * np.random.rand(3)
    alphaP = alphaP*90*degrees
    delayP = delayP*360*degrees
    delta = delta*180*degrees
    alphaR = alphaR*90*degrees
    delayR = delayR*360*degrees     
#     solution = (p1, p2, alphaP, delayP, delta, alphaR, delayR)
    # Create objects 
    M1 = Mueller('Mp')
    M1.diattenuator_charac_angles_from_Jones(p1, p2, alphaP, delayP)
    M2 = Mueller('Mr')
    M2.retarder_charac_angles_from_Jones(delta, alphaR, delayR)
    M3 = Mueller('Md')
    M3.depolarizer(d)
#     M3.from_matrix(np.eye(4))
    M = M3*M2*M1
#     print(M.checks.is_non_depolarizing())
#     print(M)
    # Decompose
    Md, Mr, Mp = M.analysis.decompose_polar(tol=1e-10, verbose = False)
    aux = [comparison(Mp.M, M1.M, eps), comparison(Mr.M, M2.M, eps), comparison(Md.M, M3.M, eps)]
    Mproposal = Md*Mr*Mp
#     print(aux)   
#     print([delta, alphaR, delayR])
#     print(Mr.analysis.retarder())
#     print("")
#     print([M3, Md])
#     print([M2, Mr])
#     print([M1, M, Mp])
    errors[ind] = comparison(M.M, Mproposal.M, eps)
print(errors)
Md, Mr, Mp, params = M.analysis.decompose_polar(tol=1e-10, verbose=True, give_all=True)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
------------------------------------------------------
The polarizer is singular.
Polar decomposition of the matrix M = Mdesp * Mr * Mp:

The depolarizer Mueller matrix is:
depolarizer = 
  [+1.000, +0.000, +0.000, +0.000]
  [-0.531, +0.000, +0.000, +0.000]
  [+0.228, +0.000, +0.000, +0.000]
  [-0.006, +0.000, +0.000, +0.000]

Parameters:
  - Polarizance = 0.5782831309714839.
  - Depolarization degree = 0.9426184488670938.

The retarder Mueller matrix is:
retarder = 
  [ +1,  +0,  +0,  +0]
  [ +0,  +1,  +0,  +0]
  [ +0,  +0,  +1,  +0]
  [ +0,  +0,  +0,  +1]

Parameters:
  - Delay = 0.0 deg.
  - Angle = 45.0 deg; Delay between components = 0.0 deg.
  - Azimuth = 45.0 deg; Ellipticity = 0.0 deg.

The diatenuator/polarizer Mueller matrix is:
diattenuator = 
  [+0.070, -0.059, +0.033, -0.017]
  [-0.059, +0.050, -0.028, +0.015]
  [+0.033, -0.028, +0.015, -0.008]
  [-0.017, +0.015, -0.008, +0.004]

Parameters:
  - p1 = 0.372793998

In [29]:
# Otras descomposiciones
N = 20
errors = np.zeros(N)
aux2 = [0, 0, 0, 0, 0]
for ind in range(N):
    # Create random parameters
    (p1a, p2a, alphaP, delayP, delta, alphaR, delayR) = np.random.rand(7)
    d = 0.95 * np.random.rand(3)
    p1 = max(p1a, p2a)
    p2 = min(p1a, p2a)
    alphaP = alphaP*90*degrees
    delayP = delayP*360*degrees
    delta = delta*180*degrees
    alphaR = alphaR*90*degrees
    delayR = delayR*360*degrees     
    # Create objects 
    M1 = Mueller('Mp')
    M1.diattenuator_charac_angles_from_Jones(p1, p2, alphaP, delayP)
    M2 = Mueller('Mr')
    M2.retarder_charac_angles_from_Jones(delta, alphaR, delayR)
    M3 = Mueller('Md')
    M3.depolarizer(d)
    # Try different decompositions
    M = M3*M1*M2
    Md, Mp, Mr = M.analysis.decompose_polar(decomposition = 'DPR', tol=1e-10, verbose = False)
    aux = [comparison(Mp.M, M1.M, eps), comparison(Mr.M, M2.M, eps), comparison(Md.M, M3.M, eps)]
    aux2[0] = all(aux)
    M = M2*M1*M3
    Mr, Mp, Md = M.analysis.decompose_polar(decomposition = 'RPD', tol=1e-10, verbose = False)
    aux = [comparison(Mp.M, M1.M, eps), comparison(Mr.M, M2.M, eps), comparison(Md.M, M3.M, eps)]
    aux2[1] = all(aux)
    M = M1*M2*M3
    Mp, Mr, Md = M.analysis.decompose_polar(decomposition = 'PRD', tol=1e-10, verbose = False)
    aux = [comparison(Mp.M, M1.M, eps), comparison(Mr.M, M2.M, eps), comparison(Md.M, M3.M, eps)]
    aux2[2] = all(aux)
    M = M1*M3*M2
    Mp, Md, Mr = M.analysis.decompose_polar(decomposition = 'PDR', tol=1e-10, verbose = False)
    aux = [comparison(Mp.M, M1.M, eps), comparison(Mr.M, M2.M, eps), comparison(Md.M, M3.M, eps)]
    aux2[3] = all(aux)
    M = M2*M3*M1
    Mr, Md, Mp = M.analysis.decompose_polar(decomposition = 'RDP', tol=1e-10, verbose = False)
    aux = [comparison(Mp.M, M1.M, eps), comparison(Mr.M, M2.M, eps), comparison(Md.M, M3.M, eps)]
    aux2[4] = all(aux)
    errors[ind] = all(aux2)
print(errors)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
