# Parameters of Stokes vectors

## import module

In [1]:
%run ../config_jupyter.ipynb

{'commit_hash': '523ed2fe5',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/luismiguel/.local/lib/python3.6/site-packages/IPython',
 'ipython_version': '7.2.0',
 'os_name': 'posix',
 'platform': 'Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.6.7 (default, Oct 22 2018, 11:32:17) \n[GCC 8.2.0]'}


In [2]:
from py_pol import degrees, np
from py_pol.stokes import Stokes
from py_pol.jones_vector import Jones_vector #no quiero, hasta que saco ellipticityíptica

3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]


## Tipos de luz

In [4]:
S_linear_0=Stokes('S_linear_0')
S_linear_0.linear_light(angle=0*degrees, intensity=1)
print(S_linear_0)
print(S_linear_0.parameters)
print(S_linear_0.parameters.help())


S_linear_0 = [ +1,  +1,  +0.  +0]

parameters:
    'intensity': 1.0
     'degree_pol': 1.0
     'degree_linear_pol': 1.0
     'degree_circular_pol': 0.0
     'ellipticity': 0.0
     'azimuth': 0.0
     'eccentricity': 1.0
     'ellipse_parameters': (0.0, 0.0, 1.0), 
     'polarized': [1.0, 1.0, 0.0, 0.0], + 'unpolarized': [0.0, 0.0, 0.0, 0.0]
Here we explain the meaning of parameters.
    intensity: intensity of the light beam.
    TODO
None


In [5]:
S_linear_45=Stokes('S_linear_45')
S_linear_45.linear_light(angle=45*degrees, intensity=1)
print(S_linear_45)
print(S_linear_45.parameters)

S_linear_45 = [ +1,  +0,  +1.  +0]

parameters:
    'intensity': 1.0
     'degree_pol': 1.0
     'degree_linear_pol': 1.0
     'degree_circular_pol': 0.0
     'ellipticity': 0.0
     'azimuth': 0.7853981633974482
     'eccentricity': 1.0
     'ellipse_parameters': (0.0, 0.7853981633974482, 1.0), 
     'polarized': [1.0, 2.220446049250313e-16, 1.0, 0.0], + 'unpolarized': [0.0, 0.0, 0.0, 0.0]


In [6]:
S_linear_90=Stokes('S_linear_90')
S_linear_90.linear_light(angle=90*degrees, intensity=1)
print(S_linear_90)
print(S_linear_90.parameters)

S_linear_90 = [ +1,  -1,  +0.  +0]

parameters:
    'intensity': 1.0
     'degree_pol': 1.0
     'degree_linear_pol': 1.0
     'degree_circular_pol': 0.0
     'ellipticity': 0.0
     'azimuth': -6.123233995736766e-17
     'eccentricity': 1.0
     'ellipse_parameters': (0.0, -6.123233995736766e-17, 1.0), 
     'polarized': [1.0, -1.0, 1.2246467991473532e-16, 0.0], + 'unpolarized': [0.0, 0.0, 0.0, 0.0]


In [7]:
S_unpolarized=Stokes('S_unpolarized')
S_unpolarized.general(alpha=0*degrees, delta=0*degrees,  intensity=1, pol_degree=0)
print(S_unpolarized)
print(S_unpolarized.parameters)

S_unpolarized = [ +1,  +0,  +0.  +0]

parameters:
    'intensity': 1.0
     'degree_pol': 0.0
     'degree_linear_pol': 0.0
     'degree_circular_pol': 0.0
     'ellipticity': nan
     'azimuth': nan
     'eccentricity': nan
     'ellipse_parameters': (nan, nan, nan), 
     'polarized': [0.0, 0.0, 0.0, 0.0], + 'unpolarized': [1.0, 0.0, 0.0, 0.0]


In [8]:
S_partial_polarized=Stokes('l_pol')
S_partial_polarized.polarized_light(intensity=1, angle=0, phase=0, pol_degree=0.5)
print(S_partial_polarized)
print(S_partial_polarized.parameters)

l_pol = [+1.000, +0.500, +0.000. +0.000]

parameters:
    'intensity': 1.0
     'degree_pol': 0.5
     'degree_linear_pol': 0.5
     'degree_circular_pol': 0.0
     'ellipticity': 0.0
     'azimuth': 0.0
     'eccentricity': 1.0
     'ellipse_parameters': (0.0, 0.0, 1.0), 
     'polarized': [0.5, 0.5, 0.0, 0.0], + 'unpolarized': [0.5, 0.0, 0.0, 0.0]


In [9]:
S_right=Stokes('S_right')
S_right.circular_light(kind='r', intensity=1)
print(S_right)
print(S_right.parameters)

S_right = [ +1,  +0,  +0.  +1]

parameters:
    'intensity': 1.0
     'degree_pol': 1.0
     'degree_linear_pol': 2.303328157969851e-16
     'degree_circular_pol': 1.0
     'ellipticity': 0.9999999999999998
     'azimuth': 0.13453908143157545
     'eccentricity': 2.1073424255447017e-08
     'ellipse_parameters': (0.9999999999999998, 0.13453908143157545, 2.1073424255447017e-08), 
     'polarized': [1.0, 2.220446049250313e-16, 6.123233995736766e-17, 1.0], + 'unpolarized': [0.0, 0.0, 0.0, 0.0]


In [10]:
S_left=Stokes('S_left')
S_left.circular_light(kind='l', intensity=1)
print(S_left)
print(S_left.parameters)
print(S_left.M)

S_left = [ +1,  +0,  +0.  -1]

parameters:
    'intensity': 1.0
     'degree_pol': 1.0
     'degree_linear_pol': 2.303328157969851e-16
     'degree_circular_pol': 1.0
     'ellipticity': -0.9999999999999998
     'azimuth': 0.13453908143157545
     'eccentricity': 2.1073424255447017e-08
     'ellipse_parameters': (-0.9999999999999998, 0.13453908143157545, 2.1073424255447017e-08), 
     'polarized': [1.0, 2.220446049250313e-16, 6.123233995736766e-17, -1.0], + 'unpolarized': [0.0, 0.0, 0.0, 0.0]
[[ 1.00000000e+00]
 [ 2.22044605e-16]
 [ 6.12323400e-17]
 [-1.00000000e+00]]


In [41]:
S_elliptical_1=Stokes('S_elliptical_1')
S_elliptical_1.polarized_light(intensity=1, angle=45*degrees, phase=45*degrees, pol_degree=1)
print(S_elliptical_1)
print(S_elliptical_1.parameters)

S_elliptical_1 = [+1.000, +0.000, +0.707. +0.707]

parameters:
    'intensity': 1.0
     'degree_pol': 1.0
     'degree_linear_pol': 0.7071067811865476
     'degree_circular_pol': 0.7071067811865475
     'ellipticity': 0.41421356237309503
     'azimuth': 0.7853981633974482
     'eccentricity': 0.9101797211244547
     'ellipse_parameters': (0.41421356237309503, 0.7853981633974482, 0.9101797211244547), 
     'polarized': [1.0, 2.220446049250313e-16, 0.7071067811865476, 0.7071067811865475], + 'unpolarized': [0.0, 0.0, 0.0, 0.0]


In [42]:
S_elliptical_2=Stokes('S_elliptical_2')
S_elliptical_2.from_elements(1,np.sqrt(1/3),np.sqrt(1/3),np.sqrt(1/3))
print(S_elliptical_2)
print(S_elliptical_2.parameters)

S_elliptical_2 = [+1.000, +0.577, +0.577. +0.577]

parameters:
    'intensity': 1.0
     'degree_pol': 1.0
     'degree_linear_pol': 0.816496580927726
     'degree_circular_pol': 0.5773502691896257
     'ellipticity': 0.3178372451957822
     'azimuth': 0.39269908169872414
     'eccentricity': 0.9481452871613908
     'ellipse_parameters': (0.3178372451957822, 0.39269908169872414, 0.9481452871613908), 
     'polarized': [1.0, 0.5773502691896257, 0.5773502691896257, 0.5773502691896257], + 'unpolarized': [0.0, 0.0, 0.0, 0.0]


In [44]:
S_elliptical_3=Jones_vector('S_elliptical_3')
S_elliptical_3.elliptical_light(a=np.sqrt(0.75), b=np.sqrt(0.25), phase=90*degrees, angle=0*degrees)
S_elliptical_3=S_elliptical_3.to_Stokes()
print(S_elliptical_3)
print(S_elliptical_3.parameters)

J = [+1.000, +0.500, +0.000. +0.866]

parameters:
    'intensity': 0.9999999999999999
     'degree_pol': 1.0
     'degree_linear_pol': 0.49999999999999994
     'degree_circular_pol': 0.8660254037844387
     'ellipticity': 0.5773502691896258
     'azimuth': 5.302876193624535e-17
     'eccentricity': 0.8164965809277259
     'ellipse_parameters': (0.5773502691896258, 5.302876193624535e-17, 0.8164965809277259), 
     'polarized': [0.9999999999999999, 0.4999999999999999, 5.302876193624534e-17, 0.8660254037844386], + 'unpolarized': [0.0, 0.0, 0.0, 0.0]


## Parametros

### Intensity

In [37]:
print(S_linear_0.parameters.intensity())

1.0


### Degree of polarization

In [38]:
print(S_linear_0.parameters.degree_polarization())

1.0


In [39]:
print(S_partial_polarized.parameters.degree_polarization())

0.5


In [40]:
print(S_unpolarized.parameters.degree_polarization())

0.0


### Degree of linear polarization

In [52]:
print(S_linear_0.parameters.degree_linear_polarization())

1.0


In [53]:
print(S_right.parameters.degree_linear_polarization())

2.303328157969851e-16


In [54]:
print(S_left.parameters.degree_linear_polarization())

2.303328157969851e-16


In [55]:
print(S_elliptical_3.parameters.degree_linear_polarization())


0.49999999999999994


### Degree of circular polarization

In [56]:
print(S_linear_0.parameters.degree_circular_polarization())

0.0


In [57]:
print(S_right.parameters.degree_circular_polarization())

1.0


In [58]:
print(S_elliptical_3.parameters.degree_circular_polarization())


0.8660254037844387


In [73]:
print(S_elliptical_2.parameters.degree_circular_polarization())

0.5773502691896257


In [74]:
print(S_elliptical_1.parameters.degree_circular_polarization())

0.7071067811865475


### Polarized_unpolarized

In [63]:
Sp, Su = S_right.parameters.polarized_unpolarized()
print(Sp)
print(Su)

[[1.00000000e+00]
 [2.22044605e-16]
 [6.12323400e-17]
 [1.00000000e+00]]
[[0.]
 [0.]
 [0.]
 [0.]]


In [65]:
Sp, Su = S_partial_polarized.parameters.polarized_unpolarized()
print(Sp)
print(Su)

[[1.00000000e+00]
 [2.22044605e-16]
 [6.12323400e-17]
 [1.00000000e+00]]
[[0.]
 [0.]
 [0.]
 [0.]]


In [67]:
Sp, Su = S_elliptical_3.parameters.polarized_unpolarized()
print(Sp)
print(Su)

[[1.00000000e+00]
 [5.00000000e-01]
 [5.30287619e-17]
 [8.66025404e-01]]
[[0.]
 [0.]
 [0.]
 [0.]]


### Ellipticity

In [64]:
print(S_linear_0.parameters.ellipticity())

0.0


In [66]:
print(S_right.parameters.ellipticity())

0.9999999999999998


In [68]:
print(S_elliptical_3.parameters.ellipticity())

0.5773502691896258


### Azimut

In [69]:
print(S_linear_0.parameters.azimuth())

0.0


In [70]:
print(S_right.parameters.azimuth())

0.13453908143157545


In [72]:
print(S_elliptical_3.parameters.azimuth())

5.302876193624535e-17


In [75]:
print(S_elliptical_2.parameters.azimuth())

0.39269908169872414


In [76]:
print(S_elliptical_1.parameters.azimuth())

0.7853981633974482


### Eccentricity

In [77]:
print(S_linear_0.parameters.eccentricity())

1.0


In [78]:
print(S_right.parameters.eccentricity())

2.1073424255447017e-08


In [80]:
print(S_elliptical_3.parameters.eccentricity())

0.8164965809277259


In [81]:
print(S_elliptical_2.parameters.eccentricity())

0.9481452871613908


In [82]:
print(S_elliptical_1.parameters.eccentricity())

0.9101797211244547
