In [6]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [11]:
from py_pol import degrees, np
from py_pol.utils import *
np.set_printoptions(precision=2)
np.set_printoptions(suppress=True)

## Put in limits

In [4]:
# Put in limits
N = 10

a = (np.random.rand(N) - 0.5) * np.pi
print(a / degrees)
b = put_in_limits(a, 'alpha')
print(b / degrees)
print('')

a = (np.random.rand(N) - 0.5) * np.pi * 4
print(a / degrees)
b = put_in_limits(a, 'delta')
print(b / degrees)
print('')


[-89.06  62.22  66.68 -55.19  67.81  -8.37  76.22  42.18 -30.52 -77.22]
[89.06 62.22 66.68 55.19 67.81  8.37 76.22 42.18 30.52 77.22]

[ 143.48 -211.12 -322.06  156.24  322.33  198.9   213.7  -112.24 -235.96
  270.33]
[143.48 148.88  37.94 156.24 322.33 198.9  213.7  247.76 124.04 270.33]



## Transform charac angles in azimuth and ellipticity

In [5]:
N=100

alpha = (np.random.rand(N)) * np.pi/2
delta = (np.random.rand(N)) * np.pi * 2
print('Alpha: ', alpha / degrees)
print('Delta: ', delta / degrees, '\n')

az, el = charac_angles_2_azimuth_elipt(alpha, delta)
print('Azimuth: ', az / degrees)
print('Ellipticity: ', el / degrees, '\n')

alpha2, delta2 = azimuth_elipt_2_charac_angles(az, el)
print('New alpha: ', alpha2 / degrees)
print('New delta: ', delta2 / degrees, '\n')

Amatch = np.abs(alpha - alpha2) < 1e-10
Dmatch = np.abs(delta - delta2) < 1e-10
print('Match alpha: ', Amatch)
print('Match delta: ', Dmatch, '\n')

Alpha:  [73.61 69.58 58.24 38.43  7.9  20.47  3.1  71.4  62.36 28.67  0.6  79.21
 64.94 86.74 15.99 77.38  5.79 73.34 17.32 49.3  49.94 52.88 76.32 22.76
 64.4  18.98  7.71 41.75 13.88 55.83 77.35 42.2  50.76 72.44 20.55 80.92
 79.29 32.1  64.67 15.03 58.37  0.67 68.55 31.52 79.55 83.33 63.47 50.18
 38.54 23.11 19.46 65.98 10.22 22.72 26.42 45.3  48.6  38.01 76.3  60.43
 17.98 85.42 78.88 14.56 35.43 65.66 67.46 80.28 67.13 89.27 65.75 81.93
  1.93 63.97 39.59 82.38 88.22 72.59 20.81 22.54 49.44 48.64 10.79 32.87
 42.62 68.12 19.71  8.56 35.24  7.58 69.09  3.08 49.39 72.06 47.06 47.81
 81.66 81.61 10.02 21.76]
Delta:  [198.05 342.42 181.74  32.36  58.99 112.07  68.21 312.96  62.86 313.98
 245.42  53.57 226.82 341.88 228.9  184.27 200.82 348.17 108.74 143.54
 190.   325.78 234.24  93.87 212.82  45.3   86.47  37.49 291.13  77.05
 132.66 160.62 182.99 201.62 257.14  86.85  55.28 118.51 142.01 169.97
  65.43  76.21 326.24 276.87 192.87 176.27  97.39 153.18 272.96 329.99
  94.27 112.99 194.

In [6]:
alpha = np.array([0, 45, 90]) * degrees
delta = 360 * degrees
print('Alpha: ', alpha / degrees)
print('Delta: ', delta / degrees, '\n')

az, el = charac_angles_2_azimuth_elipt(alpha, delta)
print('Azimuth: ', az / degrees)
print('Ellipticity: ', el / degrees, '\n')

alpha2, delta2 = azimuth_elipt_2_charac_angles(az, el)
print('New alpha: ', alpha2 / degrees)
print('New delta: ', delta2 / degrees, '\n')

Amatch = np.abs(alpha - alpha2) < 1e-10
Dmatch = np.abs(delta - delta2) < 1e-10
print('Match alpha: ', Amatch)
print('Match delta: ', Dmatch, '\n')

Alpha:  [ 0. 45. 90.]
Delta:  360.0 

Azimuth:  [ 0. 45. 90.]
Ellipticity:  [0. 0. 0.] 

New alpha:  [ 0. 45. 90.]
New delta:  [0. 0. 0.] 

Match alpha:  [ True  True  True]
Match delta:  [False False False] 



## Transform azimuth and ellipticity in charac angles

In [6]:
az = (np.random.rand(N)) * np.pi
el = (0.5 - np.random.rand(N)) * np.pi / 2
print('Azimuth: ', az / degrees)
print('Ellipticity: ', el / degrees, '\n')

alpha, delta = azimuth_elipt_2_charac_angles(az, el)
print('Alpha: ', alpha / degrees)
print('Delta: ', delta / degrees, '\n')

az2, el2 = charac_angles_2_azimuth_elipt(alpha, delta)
print('New azimuth: ', az2 / degrees)
print('New ellipticity: ', el2 / degrees, '\n')

Amatch = np.abs(az - az2) < 1e-10
Dmatch = np.abs(el - el2) < 1e-10
print('Match azimuth: ', Amatch)
print('Match ellipticity: ', Dmatch, '\n')

Azimuth:  [105.62   9.16  63.77 162.27   2.97  40.17 126.   137.86  56.     8.22
  76.63  74.13  89.86 141.07  65.49  36.76  18.24  82.08  92.62 131.02
   0.65  37.94 111.53 160.28  79.17  85.57 133.43 124.3  116.55  90.96
 108.71  25.92 140.17 174.68  70.02  55.26 130.11 114.02  76.5  121.56
  33.6   63.86 120.72  63.    19.47  32.86  80.92   5.95  75.83  55.28
 108.43  28.11  49.68   9.65  31.59  27.58  45.62  32.17 161.76  62.18
 170.6   31.46  41.66  74.53 155.43 163.83 104.84 146.43 171.46  40.22
   5.95  88.78 133.4   10.74 176.46  64.98   0.95  95.9  165.57  86.11
  64.18 131.58   9.06 167.88  69.15 150.01   4.89  60.36  94.82  19.91
 130.84 113.78   8.17 104.44  47.32  54.27  91.58 145.55 116.93 171.49]
Ellipticity:  [ 24.92  22.48  42.47   4.9  -17.15 -25.71  22.76 -30.04 -42.67 -37.79
   6.28  -1.42 -38.03 -26.66  19.54  40.7   10.96  13.04 -30.96 -20.65
  -2.14 -39.74   9.39  -8.87 -41.2  -21.31  22.45 -13.98   0.05  -5.07
  -7.68  -5.52  14.96 -19.36  31.92  38.72  44.41   

In [8]:
az = np.array([0, 45, 90, 135, 180]) * degrees
el = 45 * degrees
print('Azimuth: ', az / degrees)
print('Ellipticity: ', el / degrees, '\n')

alpha, delta = azimuth_elipt_2_charac_angles(az, el)
print('Alpha: ', alpha / degrees)
print('Delta: ', delta / degrees, '\n')

az2, el2 = charac_angles_2_azimuth_elipt(alpha, delta)
print('New azimuth: ', az2 / degrees)
print('New ellipticity: ', el2 / degrees, '\n')

Amatch = np.abs(az - az2) < 1e-10
Dmatch = np.abs(el - el2) < 1e-10
print('Match azimuth: ', Amatch)
print('Match ellipticity: ', Dmatch, '\n')

Azimuth:  [  0.  45.  90. 135. 180.]
Ellipticity:  45.0 

Alpha:  [45. 45. 45. 45. 45.]
Delta:  [270. 270. 270. 270. 270.] 

New azimuth:  [0. 0. 0. 0. 0.]
New ellipticity:  [45. 45. 45. 45. 45.] 

Match azimuth:  [ True False False False False]
Match ellipticity:  [ True  True  True  True  True] 



In [14]:
az = np.array([np.nan, np.nan, np.nan]) * degrees
el = np.array([30, 45, -45]) * degrees
print('Azimuth: ', az / degrees)
print('Ellipticity: ', el / degrees, '\n')

alpha, delta = azimuth_elipt_2_charac_angles(az, el)
print('Alpha: ', alpha / degrees)
print('Delta: ', delta / degrees, '\n')

az2, el2 = charac_angles_2_azimuth_elipt(alpha, delta)
print('New azimuth: ', az2 / degrees)
print('New ellipticity: ', el2 / degrees, '\n')

Amatch = np.abs(az - az2) < 1e-10
Dmatch = np.abs(el - el2) < 1e-10
print('Match azimuth: ', Amatch)
print('Match ellipticity: ', Dmatch, '\n')

Azimuth:  [nan nan nan]
Ellipticity:  [ 30.  45. -45.] 

[False False False] [0. 0. 0.]
[False  True  True] [0.   1.57 4.71]
[False False False] [0.   1.57 4.71]
[ True False False] [ nan 1.57 4.71]
[False False False] [ nan 1.57 4.71]
Alpha:  [nan 45. 45.]
Delta:  [ nan  90. 270.] 

New azimuth:  [nan  0.  0.]
New ellipticity:  [ nan -45.  45.] 

Match azimuth:  [False False False]
Match ellipticity:  [False False False] 



d:\codigo\py_pol\py_pol\utils.py:662: RuntimeWarning: invalid value encountered in greater
  cond2 = cond1 * (azimuth > np.pi / 2)
d:\codigo\py_pol\py_pol\utils.py:864: RuntimeWarning: invalid value encountered in greater
  q = q + 3 * (angle > np.pi / 2) * (angle < np.pi * 3 / 4)
d:\codigo\py_pol\py_pol\utils.py:864: RuntimeWarning: invalid value encountered in less
  q = q + 3 * (angle > np.pi / 2) * (angle < np.pi * 3 / 4)
d:\codigo\py_pol\py_pol\utils.py:865: RuntimeWarning: invalid value encountered in greater
  q = q + 3.5 * (angle == np.pi * 3 / 4)
d:\codigo\py_pol\py_pol\utils.py:865: RuntimeWarning: invalid value encountered in less
  q = q + 3.5 * (angle == np.pi * 3 / 4)
d:\codigo\py_pol\py_pol\utils.py:867: RuntimeWarning: invalid value encountered in greater
  q = q + 4.5 * (angle == np.pi)
d:\codigo\py_pol\py_pol\utils.py:867: RuntimeWarning: invalid value encountered in less
  q = q + 4.5 * (angle == np.pi)
d:\codigo\py_pol\py_pol\utils.py:869: RuntimeWarning: invalid va

In [6]:
a = np.array([True])
b = np.array([False])
print(a+b)

[ True]


## Rotation Jones

In [26]:
angle = 90*degrees
print(rotation_matrix_Jones(-angle))

angle = np.linspace(0, 90*degrees, 2)
M = rotation_matrix_Jones(angle)
M2 = rotation_matrix_Jones(-angle)
print(M, '\n', M2)

from py_pol.jones_matrix import Jones_matrix
J1 = Jones_matrix('+')
J1.from_matrix(M)
print(J1)
J2 = Jones_matrix('-')
J2.from_matrix(M2)
print(J2)
J3 = Jones_matrix('P')
J3.diattenuator_perfect()
print(J3)
J4 = J2 * (J3 * J1)
print(J4)

[[[ 0.]
  [-1.]]

 [[ 1.]
  [ 0.]]]
[[[ 1.  0.]
  [ 0.  1.]]

 [[-0. -1.]
  [ 1.  0.]]] 
 [[[ 1.  0.]
  [-0. -1.]]

 [[ 0.  1.]
  [ 1.  0.]]]
+ = 
[+1.000 +0.000]   [+0.000 +1.000]   
[-0.000 +1.000]   [-1.000 +0.000]   

- = 
[+1.000 -0.000]   [+0.000 -1.000]   
[+0.000 +1.000]   [+1.000 +0.000]   

P = 
[+1.000 +0.000]   
[+0.000 +0.000]   

- * P * + = 
[+1.000 +0.000]   [+0.000 +0.000]   
[+0.000 +0.000]   [+0.000 +1.000]   



In [35]:
angle = np.linspace(0, 90*degrees, 2)
M = rotation_matrix_Jones(angle)
M2 = rotation_matrix_Jones(-angle)
print(M, '\n', M2)

from py_pol.jones_matrix import Jones_matrix
J1 = Jones_matrix('+')
J1.from_matrix(M)
print(J1)
J2 = Jones_matrix('-')
J2.from_matrix(M2)
print(J2)
J3 = Jones_matrix('P')
J3.diattenuator_perfect()
print(J3)
J4 = J2 * J3
print(J4)

[[[ 1.  0.]
  [ 0.  1.]]

 [[-0. -1.]
  [ 1.  0.]]] 
 [[[ 1.  0.]
  [-0. -1.]]

 [[ 0.  1.]
  [ 1.  0.]]]
[2 2 2]
0 1
+ = 
[+1.000 +0.000]   [+0.000 +1.000]   
[-0.000 +1.000]   [-1.000 +0.000]   

[2 2 2]
0 1
- = 
[+1.000 -0.000]   [+0.000 -1.000]   
[+0.000 +1.000]   [+1.000 +0.000]   

[2 2 1]
0 1
[2 2 1]
0 1
[2 2 1]
0 1
P = 
[+1.000 +0.000]   
[+0.000 +0.000]   

[2 2 2]
0 1
[2 2 2]
0 1
- * P = 
[+1.000 +0.000]   [+0.000 +0.000]   
[+0.000 +1.000]   [+0.000 +0.000]   



d:\codigo\py_pol\py_pol\jones_matrix.py:514: ComplexWarning: Casting complex values to real discards the imaginary part
  self.M = np.array(self.M, dtype=float)


In [33]:
np.argmin(np.array([2,2,1])==2)

2

## Inverse_pypol

In [9]:
M1 = np.array([[1, 2], [3,5]])
M1 = np.linalg.inv(M1)
print(M1)

M2 = np.array([[[1], [2]], [[3],[5]]])
M2 = inv_pypol(M2)
print(M2)

[[-5.  2.]
 [ 3. -1.]]
[[[-5.]
  [ 2.]]

 [[ 3.]
  [-1.]]]


## matmul_pypol

In [20]:
M1 = np.array([[[1], [2]], [[3],[5]]])
M2 = np.array([[[0], [1]], [[10], [100]]])
M = matmul_pypol(M1, M2)
print(M)
print(M1.shape, M.shape)

M1 = np.array([[[1], [2]], [[3],[5]]])
M2 = np.array([[0], [1]])
M = matmul_pypol(M1, M2)
print(M)
print(M1.shape, M.shape)

[[[ 20]
  [201]]

 [[ 50]
  [503]]]
(2, 2, 1) (2, 2, 1)
[[[2]]

 [[5]]]
(2, 2, 1) (2, 1, 1)
