# Decimals for good representation of numbers

In [23]:
from py_pol import np, degrees
from py_pol.jones_vector import Jones_vector
from py_pol.mueller import Mueller

In [34]:
num_decimals=4 
np.set_printoptions(precision=6)

In [35]:
j0 = Jones_vector('j0')
j0.linear_light(amplitude=1, angle=45*degrees)
print(j0)

j0 = [0.7071; 0.7071]'


In [36]:
print(j0.M)

[[0.707107]
 [0.707107]]


In [37]:
j0.M=np.round(j0.M, num_decimals)
print(j0.M)

[[0.7071]
 [0.7071]]


In [38]:
M0=Mueller('m0')
M0.diattenuator_linear(p1=0.9, p2=0.1,angle=-22.5*degrees)
print(M0)

m0 @-22.50º = 
  [+0.410, +0.283, -0.283, +0.000]
  [+0.283, +0.250, -0.160, +0.000]
  [-0.283, -0.160, +0.250, +0.000]
  [+0.000, +0.000, +0.000, +0.090]



In [39]:
print(M0.name, " = ")
print(np.round(M0.M,3))

m0 @-22.50º  = 
[[ 0.41   0.283 -0.283  0.   ]
 [ 0.283  0.25  -0.16   0.   ]
 [-0.283 -0.16   0.25   0.   ]
 [ 0.     0.     0.     0.09 ]]


In [22]:
num_decimals=2

M = np.array(M0.M).squeeze()
M = np.round(M, num_decimals)
l_name = "{} = \n".format(M0.name)
difference = abs(M.round() - M).sum()

In [20]:
l0 = "  [{:+4.4f}, {:+4.4f}, {:+4.4f}, {:+4.4f}]\n".format(
    M[0, 0], M[0, 1], M[0, 2], M[0, 3])
l1 = "  [{:+4.4f}, {:+4.4f}, {:+4.4f}, {:+4.4f}]\n".format(
    M[1, 0], M[1, 1], M[1, 2], M[1, 3])
l2 = "  [{:+4.4f}, {:+4.4f}, {:+4.4f}, {:+4.4f}]\n".format(
    M[2, 0], M[2, 1], M[2, 2], M[2, 3])
l3 = "  [{:+4.4f}, {:+4.4f}, {:+4.4f}, {:+4.4f}]\n".format(
    M[3, 0], M[3, 1], M[3, 2], M[3, 3])

print(l_name + l0 + l1 + l2 + l3)

m0 @-22.50º = 
  [+0.4100, +0.2800, -0.2800, +0.0000]
  [+0.2800, +0.2500, -0.1600, +0.0000]
  [-0.2800, -0.1600, +0.2500, +0.0000]
  [+0.0000, +0.0000, +0.0000, +0.0900]



In [10]:
l0 = "   {}\n".format(M[:,0])
l1 = "   {}\n".format(M[:,1])
l2 = "   {}\n".format(M[:,2])
l3 = "   {}\n".format(M[:,3])

print(l_name + l0 + l1 + l2 + l3)

m0 @-45.00º = 
   [ 0.41  0.   -0.4   0.  ]
   [ 0.    0.09 -0.    0.  ]
   [-0.4  -0.    0.41  0.  ]
   [0.   0.   0.   0.09]



In [17]:
l0 = "  [{:+4.4f}, {:+4.4f}, {:+4.4f}, {:+4.4f}]\n".format(
    M[0, 0], M[0, 1], M[0, 2], M[0, 3])
l1 = "  [{:+4.4f}, {:+4.4f}, {:+4.4f}, {:+4.4f}]\n".format(
    M[1, 0], M[1, 1], M[1, 2], M[1, 3])
l2 = "  [{:+4.4f}, {:+4.4f}, {:+4.4f}, {:+4.4f}]\n".format(
    M[2, 0], M[2, 1], M[2, 2], M[2, 3])
l3 = "  [{:+4.4f}, {:+4.4f}, {:+4.4f}, {:+4.4f}]\n".format(
    M[3, 0], M[3, 1], M[3, 2], M[3, 3])

print(l_name + l0 + l1 + l2 + l3)

m0 @-45.00º = 
  [+0.4100, +0.0000, -0.4000, +0.0000]
  [+0.0000, +0.0900, -0.0000, +0.0000]
  [-0.4000, -0.0000, +0.4100, +0.0000]
  [+0.0000, +0.0000, +0.0000, +0.0900]



In [18]:
l0 = "   {}\n".format(M[:,0])
l1 = "   {}\n".format(M[:,1])
l2 = "   {}\n".format(M[:,2])
l3 = "   {}\n".format(M[:,3])

print(l_name + l0 + l1 + l2 + l3)

m0 @-45.00º = 
   [ 0.41  0.   -0.4   0.  ]
   [ 0.    0.09 -0.    0.  ]
   [-0.4  -0.    0.41  0.  ]
   [0.   0.   0.   0.09]

