Había un error en 

    def _actualize_(f):
        @wraps(f)
        def wrapped(inst, *args, **kwargs):
            f(inst, *args, **kwargs)
            inst.update()
            return

        return wrapped

Que pasa a
        
    def _actualize_(f):
        @wraps(f)
        def wrapped(inst, *args, **kwargs):
            result = f(inst, *args, **kwargs)
            inst.update()
            return result

        return wrapped
        
        
Ocurría que los métodos aunque tenían return self.M solo sacaban None

In [1]:
from math import sqrt

from py_pol.mueller import Mueller
from py_pol.stokes import Stokes
from py_pol.jones_matrix import Jones_matrix
from py_pol.utils import rotation_matrix_Mueller, isrow, iscolumn, azimuth_elipt_2_charac_angles

from py_pol import degrees
import numpy as np

eps = 1e-6

In [5]:
M1 = Mueller('M1')
M1.diattenuator_linear(p1=1, p2=0, angle=45*degrees)
print(M1)
print(M1.M, sep=';;', end='\n\n')

M1 @45.00º = 
  [+0.500, +0.000, +0.500, +0.000]
  [+0.000, +0.000, +0.000, +0.000]
  [+0.500, +0.000, +0.500, +0.000]
  [+0.000, +0.000, +0.000, +0.000]

[[5.00000000e-01 3.06161700e-17 5.00000000e-01 0.00000000e+00]
 [3.06161700e-17 1.87469973e-33 3.06161700e-17 0.00000000e+00]
 [5.00000000e-01 3.06161700e-17 5.00000000e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]]



In [16]:
M2=M1.rotate(angle=45*degrees, keep=True)
M2=np.round(M2,3)
print(M1,'\n')
print(M2)

M1 @45.00º @45.00º @45.00º @45.00º @45.00º @45.00º @45.00º @45.00º @45.00º @45.00º @45.00º = 
  [+0.500, -0.000, -0.500, +0.000]
  [-0.000, +0.000, +0.000, +0.000]
  [-0.500, +0.000, +0.500, +0.000]
  [+0.000, +0.000, +0.000, +0.000]
 

[[ 0.5 -0.  -0.5  0. ]
 [-0.   0.   0.   0. ]
 [-0.5  0.   0.5  0. ]
 [ 0.   0.   0.   0. ]]


In [26]:
asdf[1][:-2]

'45.00'